export {IGroupType} from "./groupType";
export {IGroupMapType} from "./groupMapType";
export {ILMSMapType} from "./lmsMapType";
export {ISubjectsConstructor} from "./subjectConstructor";
export {ISubjectsType} from "./subjectType";
export {ITeacherType} from "./teacherType";
export {ITeacherMapType} from "./teacherMapType";
export {IPupilType} from "./pupilType";
export {IPupilMapType} from "./pupilMapType";
